import { relations, sql, type SQL } from "drizzle-orm";
import {
  type AnyPgColumn,
  boolean,
  customType,
  date,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  primaryKey,
  real,
  text,
  timestamp,
  unique,
  uniqueIndex,
  uuid,
  vector,
} from "drizzle-orm/pg-core";
import type { Ingredient, RecipeNutrition, Step } from "@seconds/core";

/**
 * The full Second Breakfast data model. Only the recipe/import path is wired up in the
 * app today, but shelves, ratings, friends, pantry, and lists are defined here
 * so later slices land as features rather than migrations of live data.
 */

/**
 * Postgres full-text search vector. Generated by the database from the recipe's
 * own columns, so it can never drift from what it indexes.
 */
const tsvector = customType<{ data: string; driverData: string }>({
  dataType: () => "tsvector",
});

export const sourceKind = pgEnum("source_kind", [
  "youtube", "tiktok", "instagram", "facebook", "web", "manual", "text",
]);

export const extractionMethod = pgEnum("extraction_method", [
  "schema-org", "article-llm", "transcript-llm", "caption-llm", "manual",
]);

/** Mirrors Goodreads' want-to-read / reading / read triad. */
export const shelfType = pgEnum("shelf_type", ["want_to_cook", "cooking", "cooked", "custom"]);

export const visibility = pgEnum("visibility", ["private", "friends", "public"]);

export const mealSlot = pgEnum("meal_slot", ["breakfast", "lunch", "dinner"]);

export const friendshipStatus = pgEnum("friendship_status", ["pending", "accepted", "blocked"]);

/**
 * Plan identifiers, not marketing names. `@seconds/core` maps these to whatever
 * the tiers are currently called, so a rename is a label change rather than a
 * migration.
 */
export const userTier = pgEnum("user_tier", ["free", "plus", "pro"]);

/** Which pool a credit came out of. The allowance expires; purchases don't. */
export const creditSource = pgEnum("credit_source", ["allowance", "purchased"]);

export const importStatus = pgEnum("import_status", [
  "queued", "resolving", "extracting", "ready", "failed",
]);

// ---------------------------------------------------------------- people

export const users = pgTable(
  "users",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    /**
     * Clerk's user id. Nullable only so a local dev run works before Clerk keys
     * are configured; every real account has one.
     */
    clerkId: text("clerk_id"),
    email: text("email").notNull(),
    handle: text("handle").notNull(),
    displayName: text("display_name").notNull(),
    avatarUrl: text("avatar_url"),
    tier: userTier("tier").notNull().default("free"),
    /** Stripe's customer id, so a returning buyer isn't created twice. */
    stripeCustomerId: text("stripe_customer_id"),
    /** The live subscription, when there is one. Null on the free tier. */
    stripeSubscriptionId: text("stripe_subscription_id"),
    /**
     * Every credit ever bought, not the remaining balance. What's left is this
     * minus the purchased spends in the ledger, which keeps the balance
     * derivable from rows rather than being a mutable number two writers could
     * race each other to update.
     */
    creditsPurchased: integer("credits_purchased").notNull().default(0),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("users_clerk_idx").on(t.clerkId),
    uniqueIndex("users_email_idx").on(t.email),
    uniqueIndex("users_handle_idx").on(t.handle),
    uniqueIndex("users_stripe_customer_idx").on(t.stripeCustomerId),
    // The subscription webhooks arrive knowing the subscription, not the user.
    index("users_stripe_subscription_idx").on(t.stripeSubscriptionId),
  ],
);

/**
 * One row per direction, so "who are my friends" is a single indexed lookup
 * and a pending request is distinguishable from an accepted one.
 */
export const friendships = pgTable(
  "friendships",
  {
    userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    friendId: uuid("friend_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    status: friendshipStatus("status").notNull().default("pending"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.friendId] }), index("friendships_friend_idx").on(t.friendId)],
);

/**
 * Every Stripe event this app has already acted on.
 *
 * Stripe retries a webhook until it gets a 2xx, and a retry that granted
 * credits a second time would be handing out money. The event id is the
 * primary key, so a duplicate insert fails and the handler knows to stop
 * rather than fulfil again.
 *
 * Kept forever on purpose. It's a few bytes a row, and "did we already
 * process this?" is a question that can be asked about an event from any point
 * in the past.
 */
export const stripeEvents = pgTable("stripe_events", {
  /** Stripe's own event id — `evt_...`. */
  id: text("id").primaryKey(),
  type: text("type").notNull(),
  processedAt: timestamp("processed_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * What someone bought, and what it did to their account.
 *
 * Separate from `credit_spends` because they answer different questions: one
 * is where credits went, this is where they came from. Together they're the
 * whole story of a balance.
 */
export const creditPurchases = pgTable(
  "credit_purchases",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    /** The product id from `@seconds/core` — `pack-25`, `plan-pro`. */
    productId: text("product_id").notNull(),
    /** Whole cents actually charged, as reported by Stripe rather than assumed. */
    cents: integer("cents").notNull(),
    credits: integer("credits").notNull().default(0),
    tier: userTier("tier"),
    /** Stripe's checkout session id, for reconciling against their dashboard. */
    stripeSessionId: text("stripe_session_id"),
    /**
     * Null until the credits/tier this purchase paid for have actually been
     * applied. The neon-http driver has no interactive transactions, so the
     * insert of this row and the write that fulfils it are two separate
     * statements — if the process dies between them, this column is what
     * tells a retry to finish the job instead of treating a claimed-but-
     * unfulfilled row as "already done."
     */
    fulfilledAt: timestamp("fulfilled_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("credit_purchases_user_idx").on(t.userId),
    // One row per checkout session, so a replayed fulfilment can't duplicate a
    // purchase even if the event-level guard were somehow bypassed.
    uniqueIndex("credit_purchases_session_idx").on(t.stripeSessionId),
  ],
);

/**
 * One row per AI import that cost a credit.
 *
 * A ledger rather than a counter, because this is the only part of the app
 * that touches money. When someone asks why they were charged, the answer has
 * to be a list of things they did, not a number that went down.
 *
 * Nothing is written here for a schema.org or hand-typed recipe — those never
 * call a model, so they never spend anything.
 */
export const creditSpends = pgTable(
  "credit_spends",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    /** `YYYY-MM` in UTC. Text because the only question asked of it is equality. */
    month: text("month").notNull(),
    source: creditSource("source").notNull(),
    /**
     * Nulled rather than cascaded when the recipe goes: deleting a recipe must
     * not refund the model call that was already paid for.
     */
    recipeId: uuid("recipe_id").references(() => recipes.id, { onDelete: "set null" }),
    method: extractionMethod("method").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // The hot query: how much of this month's allowance is gone.
    index("credit_spends_user_month_idx").on(t.userId, t.month, t.source),
    index("credit_spends_user_source_idx").on(t.userId, t.source),
  ],
);

// ---------------------------------------------------------------- recipes

export const recipes = pgTable(
  "recipes",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    ownerId: uuid("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }),

    title: text("title").notNull(),
    description: text("description"),
    imageUrl: text("image_url"),

    servings: integer("servings"),
    servingsNote: text("servings_note"),
    prepMinutes: integer("prep_minutes"),
    cookMinutes: integer("cook_minutes"),
    totalMinutes: integer("total_minutes"),

    /**
     * Ingredients and steps are stored as JSONB rather than child tables: they
     * are always read and written as a whole card, never queried row-by-row.
     * Ingredient *search* goes through `recipeIngredients` below instead.
     */
    ingredients: jsonb("ingredients").$type<Ingredient[]>().notNull(),
    steps: jsonb("steps").$type<Step[]>().notNull(),
    equipment: text("equipment").array().notNull().default([]),
    tags: text("tags").array().notNull().default([]),

    cuisine: text("cuisine"),
    course: text("course"),
    difficulty: text("difficulty"),

    sourceKind: sourceKind("source_kind").notNull(),
    sourceUrl: text("source_url"),
    sourceAuthor: text("source_author"),
    sourceSiteName: text("source_site_name"),
    extractionMethod: extractionMethod("extraction_method").notNull(),
    /** 0-1 from the extractor; drives the "double-check this" badge. */
    confidence: real("confidence").notNull().default(1),
    extractionNotes: text("extraction_notes").array().notNull().default([]),
    /** Set once a human has reviewed an imported card. */
    verifiedAt: timestamp("verified_at", { withTimezone: true }),

    visibility: visibility("visibility").notNull().default("private"),
    /** Set the first time a recipe is shared, so a link can be revoked and reissued. */
    sharedAt: timestamp("shared_at", { withTimezone: true }),

    /**
     * Per-serving nutrition, when it's known. Null for a recipe nobody has
     * asked about yet — computing it up front for every import would spend a
     * model call and a USDA lookup that most recipes never need.
     */
    nutrition: jsonb("nutrition").$type<RecipeNutrition>(),

    /**
     * The recipe this was saved from, when someone copied a shared link.
     * Kept so a shared recipe can say how many people have saved it, and so
     * credit points back at whoever did the importing work.
     */
    copiedFromId: uuid("copied_from_id").references((): AnyPgColumn => recipes.id, {
      // Losing the original shouldn't delete everyone's saved copy; it just
      // loses the trail back to it.
      onDelete: "set null",
    }),

    /** Title + tags + ingredients, embedded for semantic discovery and pantry search. */
    embedding: vector("embedding", { dimensions: 1024 }),

    /**
     * What discovery searches over. Title outranks cuisine, which outranks the
     * description, so "chili" finds the chili recipe before it finds one that
     * merely mentions chili in a paragraph.
     *
     * Tags are deliberately not in here. `array_to_string` is only STABLE, so
     * including them makes the whole expression non-immutable and Postgres
     * refuses the generated column — and tags want exact matching anyway
     * ("vegetarian", not a stemmed near-miss), which the GIN index on the
     * array below does better.
     */
    searchVector: tsvector("search_vector").generatedAlwaysAs(
      (): SQL => sql`
        setweight(to_tsvector('english'::regconfig, coalesce(${recipes.title}, '')), 'A') ||
        setweight(to_tsvector('english'::regconfig, coalesce(${recipes.cuisine}, '')), 'B') ||
        setweight(to_tsvector('english'::regconfig, coalesce(${recipes.description}, '')), 'C')
      `,
    ),

    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("recipes_owner_idx").on(t.ownerId, t.createdAt),
    index("recipes_visibility_idx").on(t.visibility, t.createdAt),
    // Re-importing the same link should update the existing card, not duplicate it.
    uniqueIndex("recipes_owner_source_idx").on(t.ownerId, t.sourceUrl).where(sql`${t.sourceUrl} is not null`),
    // "how many people saved this" is a count over this column.
    index("recipes_copied_from_idx").on(t.copiedFromId),
    // Discovery searches this; GIN is the index type tsvector wants.
    index("recipes_search_idx").using("gin", t.searchVector),
    // Tag filtering uses array overlap, which GIN also serves.
    index("recipes_tags_idx").using("gin", t.tags),
  ],
);

/**
 * Flattened ingredient index. One row per (recipe, canonical ingredient), which
 * is what "what can I make from what's in my kitchen" actually joins against —
 * a JSONB containment query over the card can't be indexed usefully at scale.
 */
export const recipeIngredients = pgTable(
  "recipe_ingredients",
  {
    recipeId: uuid("recipe_id").notNull().references(() => recipes.id, { onDelete: "cascade" }),
    canonicalItem: text("canonical_item").notNull(),
    optional: boolean("optional").notNull().default(false),
    /** True for salt, oil, and the like — missing these shouldn't disqualify a match. */
    isStaple: boolean("is_staple").notNull().default(false),
  },
  (t) => [
    primaryKey({ columns: [t.recipeId, t.canonicalItem] }),
    index("recipe_ingredients_item_idx").on(t.canonicalItem),
  ],
);

// ---------------------------------------------------------------- imports

/** An in-flight or finished import, so the UI can show progress and failures survive a refresh. */
export const imports = pgTable(
  "imports",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    url: text("url"),
    rawText: text("raw_text"),
    status: importStatus("status").notNull().default("queued"),
    recipeId: uuid("recipe_id").references(() => recipes.id, { onDelete: "set null" }),
    /** The pipeline trace — which resolver ran, whether a model call was needed. */
    trace: text("trace").array().notNull().default([]),
    error: text("error"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    finishedAt: timestamp("finished_at", { withTimezone: true }),
  },
  (t) => [index("imports_user_idx").on(t.userId, t.createdAt)],
);

// ---------------------------------------------------------------- shelves & ratings

export const shelves = pgTable(
  "shelves",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    type: shelfType("type").notNull().default("custom"),
    visibility: visibility("visibility").notNull().default("private"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    unique("shelves_user_name_key").on(t.userId, t.name),
    // At most one shelf per built-in status, so "which status is this recipe at"
    // is always a single unambiguous answer.
    uniqueIndex("shelves_user_status_idx")
      .on(t.userId, t.type)
      .where(sql`${t.type} <> 'custom'`),
  ],
);

export const shelfRecipes = pgTable(
  "shelf_recipes",
  {
    shelfId: uuid("shelf_id").notNull().references(() => shelves.id, { onDelete: "cascade" }),
    recipeId: uuid("recipe_id").notNull().references(() => recipes.id, { onDelete: "cascade" }),
    addedAt: timestamp("added_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.shelfId, t.recipeId] }), index("shelf_recipes_recipe_idx").on(t.recipeId)],
);

export const ratings = pgTable(
  "ratings",
  {
    userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    recipeId: uuid("recipe_id").notNull().references(() => recipes.id, { onDelete: "cascade" }),
    stars: integer("stars").notNull(),
    review: text("review"),
    /** Times this person has actually cooked it — a stronger signal than stars alone. */
    timesCooked: integer("times_cooked").notNull().default(0),
    lastCookedAt: timestamp("last_cooked_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.recipeId] }), index("ratings_recipe_idx").on(t.recipeId)],
);

/**
 * What someone plans to cook, and when.
 *
 * The date is a `date` column rather than a timestamp on purpose: a meal
 * planned for Tuesday is planned for Tuesday, not for an instant that lands on
 * Monday for anyone far enough west.
 *
 * The key allows several recipes in one slot — a main and a side is the normal
 * case — while making the same recipe twice in one sitting impossible, which
 * is only ever a double-tap.
 */
export const mealPlanEntries = pgTable(
  "meal_plan_entries",
  {
    userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    recipeId: uuid("recipe_id").notNull().references(() => recipes.id, { onDelete: "cascade" }),
    date: date("date").notNull(),
    slot: mealSlot("slot").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.userId, t.date, t.slot, t.recipeId] }),
    // "What's this week" is the only read that matters, and it's this index.
    index("meal_plan_user_date_idx").on(t.userId, t.date),
    index("meal_plan_recipe_idx").on(t.recipeId),
  ],
);

// ---------------------------------------------------------------- pantry, lists, carts

export const pantryItems = pgTable(
  "pantry_items",
  {
    userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    canonicalItem: text("canonical_item").notNull(),
    displayName: text("display_name").notNull(),
    quantity: real("quantity"),
    unit: text("unit"),
    /** Always-on-hand items the matcher can assume without the user re-adding them. */
    isStaple: boolean("is_staple").notNull().default(false),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.canonicalItem] })],
);

export const shoppingLists = pgTable("shopping_lists", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  name: text("name").notNull().default("Shopping list"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const shoppingListItems = pgTable(
  "shopping_list_items",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    listId: uuid("list_id").notNull().references(() => shoppingLists.id, { onDelete: "cascade" }),
    canonicalItem: text("canonical_item").notNull(),
    displayName: text("display_name").notNull(),
    /** Summed across every recipe on the list, per unit. */
    quantity: real("quantity"),
    unit: text("unit"),
    /** Which recipes contributed this line, so the user can see why it's here. */
    recipeIds: uuid("recipe_ids").array().notNull().default([]),
    checked: boolean("checked").notNull().default(false),
  },
  (t) => [
    index("shopping_list_items_list_idx").on(t.listId),
    // One line per ingredient per list — merging is the whole point, so a
    // second add of the same item must update rather than duplicate.
    uniqueIndex("shopping_list_items_item_idx").on(t.listId, t.canonicalItem),
  ],
);

/**
 * A shopper's link to a grocery service they've signed in to.
 *
 * Only Kroger needs one today: its Cart API writes to a *customer's* cart, so
 * it takes an OAuth token belonging to that person, and it prices and stocks
 * per store, so the chosen location lives here too.
 *
 * The access and refresh tokens are live grocery-account credentials, so they
 * are encrypted with an application key (`GROCERY_TOKEN_ENCRYPTION_KEY`) before
 * they are written and decrypted on read — see `crypto.ts`. Storage-at-rest
 * encryption alone wouldn't help against a leaked backup or a stray read; the
 * key lives in the environment, not the database. Values carry an `enc:v1:`
 * tag, so a pre-encryption row still reads until the backfill converts it.
 */
export const groceryConnections = pgTable(
  "grocery_connections",
  {
    userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    provider: text("provider").notNull(),
    accessToken: text("access_token").notNull(),
    refreshToken: text("refresh_token"),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    /** Kroger prices, stocks, and carries different things per store. */
    locationId: text("location_id"),
    locationName: text("location_name"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.provider] })],
);

/**
 * Record of pushing a list to a grocery or delivery service. Instacart and
 * Kroger have real cart APIs; the rest are deep links, and we keep the same
 * row shape for both so the history reads consistently.
 */
export const cartHandoffs = pgTable(
  "cart_handoffs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    listId: uuid("list_id").notNull().references(() => shoppingLists.id, { onDelete: "cascade" }),
    provider: text("provider").notNull(),
    /** The URL we sent the user to — a provider cart page or a search deep link. */
    handoffUrl: text("handoff_url").notNull(),
    /** Items we could not map to the provider's catalogue. */
    unmatchedItems: text("unmatched_items").array().notNull().default([]),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("cart_handoffs_list_idx").on(t.listId)],
);

// ---------------------------------------------------------------- meal templates

/**
 * A named, reusable meal — a main plus whichever side, drink, and dessert go
 * with it. Built from the same picks a "full meal" nutrition total already
 * uses; saving one just gives that combination a name and, optionally, a
 * link to hand someone else.
 */
export const mealTemplates = pgTable("meal_templates", {
  id: uuid("id").primaryKey().defaultRandom(),
  ownerId: uuid("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  visibility: visibility("visibility").notNull().default("private"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const templateRole = pgEnum("template_role", ["main", "side", "drink", "dessert"]);

/**
 * One recipe per role per template — at most one main, one side, one drink,
 * one dessert, the same shape the full-meal total already assumes.
 */
export const mealTemplateItems = pgTable(
  "meal_template_items",
  {
    templateId: uuid("template_id").notNull().references(() => mealTemplates.id, { onDelete: "cascade" }),
    role: templateRole("role").notNull(),
    recipeId: uuid("recipe_id").notNull().references(() => recipes.id, { onDelete: "cascade" }),
  },
  (t) => [primaryKey({ columns: [t.templateId, t.role] })],
);

// ---------------------------------------------------------------- relations

export const usersRelations = relations(users, ({ many }) => ({
  recipes: many(recipes),
  shelves: many(shelves),
  ratings: many(ratings),
  pantryItems: many(pantryItems),
}));

export const recipesRelations = relations(recipes, ({ one, many }) => ({
  owner: one(users, { fields: [recipes.ownerId], references: [users.id] }),
  ingredientIndex: many(recipeIngredients),
  shelfEntries: many(shelfRecipes),
  ratings: many(ratings),
}));

export const shelvesRelations = relations(shelves, ({ one, many }) => ({
  user: one(users, { fields: [shelves.userId], references: [users.id] }),
  entries: many(shelfRecipes),
}));

export const shelfRecipesRelations = relations(shelfRecipes, ({ one }) => ({
  shelf: one(shelves, { fields: [shelfRecipes.shelfId], references: [shelves.id] }),
  recipe: one(recipes, { fields: [shelfRecipes.recipeId], references: [recipes.id] }),
}));

export const recipeIngredientsRelations = relations(recipeIngredients, ({ one }) => ({
  recipe: one(recipes, { fields: [recipeIngredients.recipeId], references: [recipes.id] }),
}));
