import { relations, sql, type SQL } from "drizzle-orm";
import {
  type AnyPgColumn,
  boolean,
  customType,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  primaryKey,
  real,
  text,
  timestamp,
  unique,
  uniqueIndex,
  uuid,
  vector,
} from "drizzle-orm/pg-core";
import type { Ingredient, Step } from "@nomnom/core";

/**
 * The full NomNom data model. Only the recipe/import path is wired up in the
 * app today, but shelves, ratings, friends, pantry, and lists are defined here
 * so later slices land as features rather than migrations of live data.
 */

/**
 * Postgres full-text search vector. Generated by the database from the recipe's
 * own columns, so it can never drift from what it indexes.
 */
const tsvector = customType<{ data: string; driverData: string }>({
  dataType: () => "tsvector",
});

export const sourceKind = pgEnum("source_kind", [
  "youtube", "tiktok", "instagram", "facebook", "web", "manual", "text",
]);

export const extractionMethod = pgEnum("extraction_method", [
  "schema-org", "article-llm", "transcript-llm", "caption-llm", "manual",
]);

/** Mirrors Goodreads' want-to-read / reading / read triad. */
export const shelfType = pgEnum("shelf_type", ["want_to_cook", "cooking", "cooked", "custom"]);

export const visibility = pgEnum("visibility", ["private", "friends", "public"]);

export const friendshipStatus = pgEnum("friendship_status", ["pending", "accepted", "blocked"]);

export const importStatus = pgEnum("import_status", [
  "queued", "resolving", "extracting", "ready", "failed",
]);

// ---------------------------------------------------------------- people

export const users = pgTable(
  "users",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    /**
     * Clerk's user id. Nullable only so a local dev run works before Clerk keys
     * are configured; every real account has one.
     */
    clerkId: text("clerk_id"),
    email: text("email").notNull(),
    handle: text("handle").notNull(),
    displayName: text("display_name").notNull(),
    avatarUrl: text("avatar_url"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("users_clerk_idx").on(t.clerkId),
    uniqueIndex("users_email_idx").on(t.email),
    uniqueIndex("users_handle_idx").on(t.handle),
  ],
);

/**
 * One row per direction, so "who are my friends" is a single indexed lookup
 * and a pending request is distinguishable from an accepted one.
 */
export const friendships = pgTable(
  "friendships",
  {
    userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    friendId: uuid("friend_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    status: friendshipStatus("status").notNull().default("pending"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.friendId] }), index("friendships_friend_idx").on(t.friendId)],
);

// ---------------------------------------------------------------- recipes

export const recipes = pgTable(
  "recipes",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    ownerId: uuid("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }),

    title: text("title").notNull(),
    description: text("description"),
    imageUrl: text("image_url"),

    servings: integer("servings"),
    servingsNote: text("servings_note"),
    prepMinutes: integer("prep_minutes"),
    cookMinutes: integer("cook_minutes"),
    totalMinutes: integer("total_minutes"),

    /**
     * Ingredients and steps are stored as JSONB rather than child tables: they
     * are always read and written as a whole card, never queried row-by-row.
     * Ingredient *search* goes through `recipeIngredients` below instead.
     */
    ingredients: jsonb("ingredients").$type<Ingredient[]>().notNull(),
    steps: jsonb("steps").$type<Step[]>().notNull(),
    equipment: text("equipment").array().notNull().default([]),
    tags: text("tags").array().notNull().default([]),

    cuisine: text("cuisine"),
    course: text("course"),
    difficulty: text("difficulty"),

    sourceKind: sourceKind("source_kind").notNull(),
    sourceUrl: text("source_url"),
    sourceAuthor: text("source_author"),
    sourceSiteName: text("source_site_name"),
    extractionMethod: extractionMethod("extraction_method").notNull(),
    /** 0-1 from the extractor; drives the "double-check this" badge. */
    confidence: real("confidence").notNull().default(1),
    extractionNotes: text("extraction_notes").array().notNull().default([]),
    /** Set once a human has reviewed an imported card. */
    verifiedAt: timestamp("verified_at", { withTimezone: true }),

    visibility: visibility("visibility").notNull().default("private"),
    /** Set the first time a recipe is shared, so a link can be revoked and reissued. */
    sharedAt: timestamp("shared_at", { withTimezone: true }),

    /**
     * The recipe this was saved from, when someone copied a shared link.
     * Kept so a shared recipe can say how many people have saved it, and so
     * credit points back at whoever did the importing work.
     */
    copiedFromId: uuid("copied_from_id").references((): AnyPgColumn => recipes.id, {
      // Losing the original shouldn't delete everyone's saved copy; it just
      // loses the trail back to it.
      onDelete: "set null",
    }),

    /** Title + tags + ingredients, embedded for semantic discovery and pantry search. */
    embedding: vector("embedding", { dimensions: 1024 }),

    /**
     * What discovery searches over. Title outranks cuisine, which outranks the
     * description, so "chili" finds the chili recipe before it finds one that
     * merely mentions chili in a paragraph.
     *
     * Tags are deliberately not in here. `array_to_string` is only STABLE, so
     * including them makes the whole expression non-immutable and Postgres
     * refuses the generated column — and tags want exact matching anyway
     * ("vegetarian", not a stemmed near-miss), which the GIN index on the
     * array below does better.
     */
    searchVector: tsvector("search_vector").generatedAlwaysAs(
      (): SQL => sql`
        setweight(to_tsvector('english'::regconfig, coalesce(${recipes.title}, '')), 'A') ||
        setweight(to_tsvector('english'::regconfig, coalesce(${recipes.cuisine}, '')), 'B') ||
        setweight(to_tsvector('english'::regconfig, coalesce(${recipes.description}, '')), 'C')
      `,
    ),

    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("recipes_owner_idx").on(t.ownerId, t.createdAt),
    index("recipes_visibility_idx").on(t.visibility, t.createdAt),
    // Re-importing the same link should update the existing card, not duplicate it.
    uniqueIndex("recipes_owner_source_idx").on(t.ownerId, t.sourceUrl).where(sql`${t.sourceUrl} is not null`),
    // "how many people saved this" is a count over this column.
    index("recipes_copied_from_idx").on(t.copiedFromId),
    // Discovery searches this; GIN is the index type tsvector wants.
    index("recipes_search_idx").using("gin", t.searchVector),
    // Tag filtering uses array overlap, which GIN also serves.
    index("recipes_tags_idx").using("gin", t.tags),
  ],
);

/**
 * Flattened ingredient index. One row per (recipe, canonical ingredient), which
 * is what "what can I make from what's in my kitchen" actually joins against —
 * a JSONB containment query over the card can't be indexed usefully at scale.
 */
export const recipeIngredients = pgTable(
  "recipe_ingredients",
  {
    recipeId: uuid("recipe_id").notNull().references(() => recipes.id, { onDelete: "cascade" }),
    canonicalItem: text("canonical_item").notNull(),
    optional: boolean("optional").notNull().default(false),
    /** True for salt, oil, and the like — missing these shouldn't disqualify a match. */
    isStaple: boolean("is_staple").notNull().default(false),
  },
  (t) => [
    primaryKey({ columns: [t.recipeId, t.canonicalItem] }),
    index("recipe_ingredients_item_idx").on(t.canonicalItem),
  ],
);

// ---------------------------------------------------------------- imports

/** An in-flight or finished import, so the UI can show progress and failures survive a refresh. */
export const imports = pgTable(
  "imports",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    url: text("url"),
    rawText: text("raw_text"),
    status: importStatus("status").notNull().default("queued"),
    recipeId: uuid("recipe_id").references(() => recipes.id, { onDelete: "set null" }),
    /** The pipeline trace — which resolver ran, whether a model call was needed. */
    trace: text("trace").array().notNull().default([]),
    error: text("error"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    finishedAt: timestamp("finished_at", { withTimezone: true }),
  },
  (t) => [index("imports_user_idx").on(t.userId, t.createdAt)],
);

// ---------------------------------------------------------------- shelves & ratings

export const shelves = pgTable(
  "shelves",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    type: shelfType("type").notNull().default("custom"),
    visibility: visibility("visibility").notNull().default("private"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    unique("shelves_user_name_key").on(t.userId, t.name),
    // At most one shelf per built-in status, so "which status is this recipe at"
    // is always a single unambiguous answer.
    uniqueIndex("shelves_user_status_idx")
      .on(t.userId, t.type)
      .where(sql`${t.type} <> 'custom'`),
  ],
);

export const shelfRecipes = pgTable(
  "shelf_recipes",
  {
    shelfId: uuid("shelf_id").notNull().references(() => shelves.id, { onDelete: "cascade" }),
    recipeId: uuid("recipe_id").notNull().references(() => recipes.id, { onDelete: "cascade" }),
    addedAt: timestamp("added_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.shelfId, t.recipeId] }), index("shelf_recipes_recipe_idx").on(t.recipeId)],
);

export const ratings = pgTable(
  "ratings",
  {
    userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    recipeId: uuid("recipe_id").notNull().references(() => recipes.id, { onDelete: "cascade" }),
    stars: integer("stars").notNull(),
    review: text("review"),
    /** Times this person has actually cooked it — a stronger signal than stars alone. */
    timesCooked: integer("times_cooked").notNull().default(0),
    lastCookedAt: timestamp("last_cooked_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.recipeId] }), index("ratings_recipe_idx").on(t.recipeId)],
);

// ---------------------------------------------------------------- pantry, lists, carts

export const pantryItems = pgTable(
  "pantry_items",
  {
    userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    canonicalItem: text("canonical_item").notNull(),
    displayName: text("display_name").notNull(),
    quantity: real("quantity"),
    unit: text("unit"),
    /** Always-on-hand items the matcher can assume without the user re-adding them. */
    isStaple: boolean("is_staple").notNull().default(false),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.canonicalItem] })],
);

export const shoppingLists = pgTable("shopping_lists", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  name: text("name").notNull().default("Shopping list"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const shoppingListItems = pgTable(
  "shopping_list_items",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    listId: uuid("list_id").notNull().references(() => shoppingLists.id, { onDelete: "cascade" }),
    canonicalItem: text("canonical_item").notNull(),
    displayName: text("display_name").notNull(),
    /** Summed across every recipe on the list, per unit. */
    quantity: real("quantity"),
    unit: text("unit"),
    /** Which recipes contributed this line, so the user can see why it's here. */
    recipeIds: uuid("recipe_ids").array().notNull().default([]),
    checked: boolean("checked").notNull().default(false),
  },
  (t) => [
    index("shopping_list_items_list_idx").on(t.listId),
    // One line per ingredient per list — merging is the whole point, so a
    // second add of the same item must update rather than duplicate.
    uniqueIndex("shopping_list_items_item_idx").on(t.listId, t.canonicalItem),
  ],
);

/**
 * A shopper's link to a grocery service they've signed in to.
 *
 * Only Kroger needs one today: its Cart API writes to a *customer's* cart, so
 * it takes an OAuth token belonging to that person, and it prices and stocks
 * per store, so the chosen location lives here too.
 *
 * The tokens are stored as they come. Neon encrypts at rest; encrypting them
 * again with an application key would mean a key to manage and rotate, and
 * anyone who can read this table can already read `users`.
 */
export const groceryConnections = pgTable(
  "grocery_connections",
  {
    userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    provider: text("provider").notNull(),
    accessToken: text("access_token").notNull(),
    refreshToken: text("refresh_token"),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    /** Kroger prices, stocks, and carries different things per store. */
    locationId: text("location_id"),
    locationName: text("location_name"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.provider] })],
);

/**
 * Record of pushing a list to a grocery or delivery service. Instacart and
 * Kroger have real cart APIs; the rest are deep links, and we keep the same
 * row shape for both so the history reads consistently.
 */
export const cartHandoffs = pgTable(
  "cart_handoffs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    listId: uuid("list_id").notNull().references(() => shoppingLists.id, { onDelete: "cascade" }),
    provider: text("provider").notNull(),
    /** The URL we sent the user to — a provider cart page or a search deep link. */
    handoffUrl: text("handoff_url").notNull(),
    /** Items we could not map to the provider's catalogue. */
    unmatchedItems: text("unmatched_items").array().notNull().default([]),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("cart_handoffs_list_idx").on(t.listId)],
);

// ---------------------------------------------------------------- relations

export const usersRelations = relations(users, ({ many }) => ({
  recipes: many(recipes),
  shelves: many(shelves),
  ratings: many(ratings),
  pantryItems: many(pantryItems),
}));

export const recipesRelations = relations(recipes, ({ one, many }) => ({
  owner: one(users, { fields: [recipes.ownerId], references: [users.id] }),
  ingredientIndex: many(recipeIngredients),
  shelfEntries: many(shelfRecipes),
  ratings: many(ratings),
}));

export const shelvesRelations = relations(shelves, ({ one, many }) => ({
  user: one(users, { fields: [shelves.userId], references: [users.id] }),
  entries: many(shelfRecipes),
}));

export const shelfRecipesRelations = relations(shelfRecipes, ({ one }) => ({
  shelf: one(shelves, { fields: [shelfRecipes.shelfId], references: [shelves.id] }),
  recipe: one(recipes, { fields: [shelfRecipes.recipeId], references: [recipes.id] }),
}));

export const recipeIngredientsRelations = relations(recipeIngredients, ({ one }) => ({
  recipe: one(recipes, { fields: [recipeIngredients.recipeId], references: [recipes.id] }),
}));
